# Generated by Django 2.1.7 on 2019-03-13 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurante', models.CharField(max_length=50)),
                ('comida', models.CharField(max_length=30)),
                ('custos', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateTimeField()),
                ('comida', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('idade', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('tamanho', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cidade', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Pessoas'),
        ),
    ]
