# Generated by Django 2.1.7 on 2019-03-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190313_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custos',
            name='custos',
            field=models.CharField(default='6', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='dia',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='pessoa',
            field=models.CharField(default='7', max_length=30),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='restaurante',
            field=models.CharField(default='8', max_length=30),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='idade',
            field=models.DecimalField(decimal_places=0, default='2', max_digits=4),
        ),
    ]
